/**
 * Crop database seeded from FAO Irrigation Manual Module 4:
 *  - Table 20: Length of crop development stages (indicative — one
 *    representative regional variant is chosen per crop; Table 20's own
 *    footnote 1 stresses these vary by region/variety and should be
 *    supplemented with local information, which the UI lets users do
 *    per-planting).
 *  - Table 21: Single crop coefficients (Kc ini, Kc mid, Kc end) and
 *    maximum crop height.
 *  - Table 54: Root zone depth range (RZD) and allowable depletion (P).
 *  - Table 57: Yield response factor (Ky), where the crop appears in
 *    that table. Ky is left undefined for crops Table 57 does not list
 *    (Lettuce, Carrots, Cucumbers, Rice) — the Yield Response module
 *    requires the user to supply Ky for those rather than guessing.
 *
 * Covers exactly the crop list requested: vegetables (tomato, onion,
 * cabbage, potato, lettuce, carrot, pepper, cucumber), field crops
 * (maize, wheat, rice, cotton, sorghum, soybean, groundnut, sugarcane),
 * and fruit crops (banana, citrus, grapes). Custom crops can be added
 * at runtime via `createCustomCrop`.
 */
import { CropDefinition } from "./types";

export const CROP_DATABASE: CropDefinition[] = [
  {
    id: "tomato",
    name: "Tomato",
    scientificName: "Solanum lycopersicum",
    category: "vegetable",
    kcIni: 0.6,
    kcMid: 1.15,
    kcEnd: 0.8,
    stageLengthsDays: { initial: 30, development: 40, mid: 40, late: 25 },
    rootDepthMinM: 0.7,
    rootDepthMaxM: 1.5,
    allowableDepletionP: 0.4,
    maxCropHeightM: 0.6,
    ky: { vegetative: 0.4, flowering: 1.1, yieldFormation: 0.8, ripening: 0.4, total: 1.05 },
  },
  {
    id: "onion",
    name: "Onion (dry)",
    scientificName: "Allium cepa",
    category: "vegetable",
    kcIni: 0.7,
    kcMid: 1.05,
    kcEnd: 0.75,
    stageLengthsDays: { initial: 15, development: 25, mid: 70, late: 40 },
    rootDepthMinM: 0.3,
    rootDepthMaxM: 0.6,
    allowableDepletionP: 0.3,
    maxCropHeightM: 0.4,
    ky: { vegetative: 0.45, flowering: 0.8, ripening: 0.3, total: 1.1 },
  },
  {
    id: "cabbage",
    name: "Cabbage",
    scientificName: "Brassica oleracea var. capitata",
    category: "vegetable",
    kcIni: 0.7,
    kcMid: 1.05,
    kcEnd: 0.95,
    stageLengthsDays: { initial: 40, development: 60, mid: 50, late: 15 },
    rootDepthMinM: 0.5,
    rootDepthMaxM: 0.8,
    allowableDepletionP: 0.45,
    maxCropHeightM: 0.4,
    ky: { vegetative: 0.2, yieldFormation: 0.45, ripening: 0.6, total: 0.95 },
  },
  {
    id: "potato",
    name: "Potato",
    scientificName: "Solanum tuberosum",
    category: "vegetable",
    kcIni: 0.5,
    kcMid: 1.15,
    kcEnd: 0.75,
    stageLengthsDays: { initial: 25, development: 30, mid: 45, late: 30 },
    rootDepthMinM: 0.4,
    rootDepthMaxM: 0.6,
    allowableDepletionP: 0.35,
    maxCropHeightM: 0.6,
    ky: { vegetative: 0.63, yieldFormation: 0.7, ripening: 0.2, total: 1.1 },
  },
  {
    id: "lettuce",
    name: "Lettuce",
    scientificName: "Lactuca sativa",
    category: "vegetable",
    kcIni: 0.7,
    kcMid: 1.0,
    kcEnd: 0.95,
    stageLengthsDays: { initial: 25, development: 35, mid: 30, late: 10 },
    rootDepthMinM: 0.3,
    rootDepthMaxM: 0.5,
    allowableDepletionP: 0.3,
    maxCropHeightM: 0.3,
    // Ky not listed for lettuce in Table 57 — user-supplied value required.
  },
  {
    id: "carrot",
    name: "Carrot",
    scientificName: "Daucus carota",
    category: "vegetable",
    kcIni: 0.7,
    kcMid: 1.05,
    kcEnd: 0.95,
    stageLengthsDays: { initial: 30, development: 40, mid: 60, late: 20 },
    rootDepthMinM: 0.5,
    rootDepthMaxM: 1.0,
    allowableDepletionP: 0.35,
    maxCropHeightM: 0.3,
  },
  {
    id: "pepper",
    name: "Sweet pepper (bell)",
    scientificName: "Capsicum annuum",
    category: "vegetable",
    kcIni: 0.6,
    kcMid: 1.05,
    kcEnd: 0.9,
    stageLengthsDays: { initial: 30, development: 35, mid: 40, late: 20 },
    rootDepthMinM: 0.5,
    rootDepthMaxM: 1.0,
    allowableDepletionP: 0.3,
    maxCropHeightM: 0.7,
    ky: { total: 1.1 },
  },
  {
    id: "cucumber",
    name: "Cucumber (fresh market)",
    scientificName: "Cucumis sativus",
    category: "vegetable",
    kcIni: 0.6,
    kcMid: 1.0,
    kcEnd: 0.75,
    stageLengthsDays: { initial: 20, development: 30, mid: 40, late: 15 },
    rootDepthMinM: 0.7,
    rootDepthMaxM: 1.2,
    allowableDepletionP: 0.5,
    maxCropHeightM: 0.3,
  },
  {
    id: "maize",
    name: "Maize (field grain)",
    scientificName: "Zea mays",
    category: "field-crop",
    kcIni: 0.3,
    kcMid: 1.2,
    kcEnd: 0.6,
    stageLengthsDays: { initial: 30, development: 50, mid: 60, late: 40 },
    rootDepthMinM: 1.0,
    rootDepthMaxM: 1.7,
    allowableDepletionP: 0.55,
    maxCropHeightM: 2.0,
    ky: { vegetative: 0.4, flowering: 1.5, yieldFormation: 0.5, ripening: 0.2, total: 1.25 },
  },
  {
    id: "wheat",
    name: "Wheat (spring)",
    scientificName: "Triticum aestivum",
    category: "field-crop",
    kcIni: 0.3,
    kcMid: 1.15,
    kcEnd: 0.35,
    stageLengthsDays: { initial: 20, development: 25, mid: 60, late: 30 },
    rootDepthMinM: 1.0,
    rootDepthMaxM: 1.5,
    allowableDepletionP: 0.55,
    maxCropHeightM: 1.0,
    ky: { vegetative: 0.2, flowering: 0.65, yieldFormation: 0.55, total: 1.15 },
  },
  {
    id: "rice",
    name: "Rice",
    scientificName: "Oryza sativa",
    category: "field-crop",
    kcIni: 1.05,
    kcMid: 1.2,
    kcEnd: 0.75,
    stageLengthsDays: { initial: 30, development: 30, mid: 60, late: 30 },
    rootDepthMinM: 0.5,
    rootDepthMaxM: 1.0,
    allowableDepletionP: 0.2,
    maxCropHeightM: 1.0,
  },
  {
    id: "cotton",
    name: "Cotton",
    scientificName: "Gossypium hirsutum",
    category: "field-crop",
    kcIni: 0.35,
    kcMid: 1.175,
    kcEnd: 0.6,
    stageLengthsDays: { initial: 30, development: 50, mid: 60, late: 55 },
    rootDepthMinM: 1.0,
    rootDepthMaxM: 1.7,
    allowableDepletionP: 0.65,
    maxCropHeightM: 1.35,
    ky: { vegetative: 0.2, flowering: 0.5, ripening: 0.25, total: 0.85 },
  },
  {
    id: "sorghum",
    name: "Sorghum (grain)",
    scientificName: "Sorghum bicolor",
    category: "field-crop",
    kcIni: 0.3,
    kcMid: 1.05,
    kcEnd: 0.55,
    stageLengthsDays: { initial: 20, development: 35, mid: 40, late: 30 },
    rootDepthMinM: 1.0,
    rootDepthMaxM: 2.0,
    allowableDepletionP: 0.55,
    maxCropHeightM: 1.5,
    ky: { vegetative: 0.2, flowering: 0.55, yieldFormation: 0.45, ripening: 0.2, total: 0.9 },
  },
  {
    id: "soybean",
    name: "Soybean",
    scientificName: "Glycine max",
    category: "field-crop",
    kcIni: 0.4,
    kcMid: 1.15,
    kcEnd: 0.5,
    stageLengthsDays: { initial: 20, development: 30, mid: 60, late: 25 },
    rootDepthMinM: 0.6,
    rootDepthMaxM: 1.3,
    allowableDepletionP: 0.5,
    maxCropHeightM: 0.75,
    ky: { vegetative: 0.2, flowering: 0.8, yieldFormation: 1.0, total: 0.85 },
  },
  {
    id: "groundnut",
    name: "Groundnut (peanut)",
    scientificName: "Arachis hypogaea",
    category: "field-crop",
    kcIni: 0.4,
    kcMid: 1.15,
    kcEnd: 0.6,
    stageLengthsDays: { initial: 25, development: 35, mid: 45, late: 25 },
    rootDepthMinM: 0.5,
    rootDepthMaxM: 1.0,
    allowableDepletionP: 0.5,
    maxCropHeightM: 0.4,
    ky: { vegetative: 0.2, flowering: 0.8, yieldFormation: 0.6, ripening: 0.2, total: 0.7 },
  },
  {
    id: "sugarcane",
    name: "Sugarcane (ratoon)",
    scientificName: "Saccharum officinarum",
    category: "field-crop",
    kcIni: 0.4,
    kcMid: 1.25,
    kcEnd: 0.75,
    stageLengthsDays: { initial: 25, development: 70, mid: 135, late: 50 },
    rootDepthMinM: 1.2,
    rootDepthMaxM: 2.0,
    allowableDepletionP: 0.65,
    maxCropHeightM: 3.0,
    ky: { vegetative: 0.75, yieldFormation: 0.5, ripening: 0.1, total: 1.2 },
  },
  {
    id: "banana",
    name: "Banana (1st year)",
    scientificName: "Musa spp.",
    category: "fruit",
    kcIni: 0.5,
    kcMid: 1.1,
    kcEnd: 1.0,
    stageLengthsDays: { initial: 120, development: 90, mid: 120, late: 60 },
    rootDepthMinM: 0.5,
    rootDepthMaxM: 0.9,
    allowableDepletionP: 0.35,
    maxCropHeightM: 3.0,
    ky: { total: 1.275 },
  },
  {
    id: "citrus",
    name: "Citrus (70% canopy, no ground cover)",
    scientificName: "Citrus spp.",
    category: "fruit",
    kcIni: 0.7,
    kcMid: 0.65,
    kcEnd: 0.7,
    stageLengthsDays: { initial: 60, development: 90, mid: 120, late: 95 },
    rootDepthMinM: 1.2,
    rootDepthMaxM: 1.5,
    allowableDepletionP: 0.5,
    maxCropHeightM: 4.0,
    ky: { total: 0.95 },
  },
  {
    id: "grapes",
    name: "Grapes (table/raisin)",
    scientificName: "Vitis vinifera",
    category: "fruit",
    kcIni: 0.3,
    kcMid: 0.85,
    kcEnd: 0.45,
    stageLengthsDays: { initial: 20, development: 40, mid: 120, late: 60 },
    rootDepthMinM: 1.0,
    rootDepthMaxM: 2.0,
    allowableDepletionP: 0.35,
    maxCropHeightM: 2.0,
    ky: { total: 0.85 },
  },
];

export function findCrop(id: string): CropDefinition | undefined {
  return CROP_DATABASE.find((c) => c.id === id);
}

let customCropCounter = 0;

/** Module 2 requirement: "Allow Custom Crop Creation." */
export function createCustomCrop(input: Omit<CropDefinition, "id" | "isCustom">): CropDefinition {
  customCropCounter += 1;
  return { ...input, id: `custom-${Date.now()}-${customCropCounter}`, isCustom: true };
}
